services:
  issuer_oidc:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-issuer-oidc-py:latest
    ports:
      - "6005:5000"
    volumes:
      - ./config.json:/config.json:ro
      - /tmp/oidc_log_dev/:/tmp/oidc_log_dev/
    restart: unless-stopped
